spring.application.name=week17-day04-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/school
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate creates/updates tables from your entities
spring.jpa.hibernate.ddl-auto=update

# Print the SQL Hibernate generates — great for learning!
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true